{% set name = "brian2wasm" %}
{% set version = "0.4.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - brian2
    - numpy
    - jinja2
    - sympy
    - packaging
    - scipy
    - setuptools
    - pyparsing
    - emsdk

about:
  home: https://github.com/brian-team/brian2wasm
  summary: WebAssembly backend for Brian2 simulator
  description: |
    brian2wasm extends the Brian2 simulator to generate WebAssembly-compatible code
    using Emscripten. This enables running spiking neural network simulations directly
    in the browser.

extra:
  recipe-maintainers:
    - mstimberg
    - PalashChitnavis