[project]
name = "brian2wasm"
version = "0.1.0"
description = "Brian2WASM environment setup"
authors = ["Palash Chitnavis"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = "==3.13"
matplotlib = "*"
emsdk = "*"
pip = "*"
setuptools = "*"
wheel = "*"

[pypi-dependencies]
brian2 = "*"
brian2wasm = { git = "https://github.com/PalashChitnavis/brian2wasm", rev = "gsoc" }

[activation]
env = { PYTHON_VERSION = "3.13" }
scripts = ["emsdk_setup.sh"]