name: Deploy Brian2WASM Simulation to GitHub Pages

on:
  push:
    branches: [ publish ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          cache: false

      - name: Install dependencies
        run: pixi install --locked

      - name: Run setup
        run: pixi run setup

      - name: Generate simulation files
        run: |  
          cd examples  
          python -m brian2wasm ./examples/ornstein_uhlenbeck.py --no-server
        shell: pixi run bash -e {0}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'your_script'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4