name: Deploy Brian2WASM Simulation to GitHub Pages

on:
  push:
    branches: [ deploy ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SCRIPT: examples/non_reliability.py  # 👈 set this

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          cache: false

      - name: Install dependencies
        run: pixi install --locked

      - name: Run setup
        run: pixi run setup

      - name: Derive folder paths
        id: derive
        run: |
          FOLDER_PATH="${SCRIPT%.py}"
          FOLDER_NAME=$(basename "$FOLDER_PATH")
          echo "FOLDER_PATH=$FOLDER_PATH" >> $GITHUB_ENV
          echo "FOLDER_NAME=$FOLDER_NAME" >> $GITHUB_ENV

      - name: Generate simulation files
        run: |
          python -m brian2wasm $SCRIPT --no-server
        shell: pixi run bash -e {0}

      - name: Prepare deploy folder
        run: |
          rm -rf $FOLDER_NAME
          mkdir -p $FOLDER_NAME
          cp $FOLDER_PATH/brian.js \
             $FOLDER_PATH/index.html \
             $FOLDER_PATH/wasm_module.js \
             $FOLDER_PATH/wasm_module.wasm \
             $FOLDER_PATH/worker.js \
             $FOLDER_NAME/
      
          # 👇 Set this to your own template if you want a custom index.html
          TEMPLATE="brian2wasm/index_template.html"
          cp "$TEMPLATE" index.html
      
          LINKS=""
          for d in */ ; do
            if [ -f "$d/index.html" ]; then
              NAME=$(basename "$d")
              LINKS="$LINKS<li><a href=\"$NAME/\">$NAME</a></li>\n"
            fi
          done
      
          sed -i "/{{LINKS}}/{
            s/{{LINKS}}//g
            r /dev/stdin
          }" index.html <<< "$LINKS"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages